// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.2
// source: api/v1/jit.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Jit_Calculate_FullMethodName = "/v1.Jit/Calculate"
)

// JitClient is the client API for Jit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JitClient interface {
	Calculate(ctx context.Context, in *CalculationRequest, opts ...grpc.CallOption) (*CalculationResponse, error)
}

type jitClient struct {
	cc grpc.ClientConnInterface
}

func NewJitClient(cc grpc.ClientConnInterface) JitClient {
	return &jitClient{cc}
}

func (c *jitClient) Calculate(ctx context.Context, in *CalculationRequest, opts ...grpc.CallOption) (*CalculationResponse, error) {
	out := new(CalculationResponse)
	err := c.cc.Invoke(ctx, Jit_Calculate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JitServer is the server API for Jit service.
// All implementations must embed UnimplementedJitServer
// for forward compatibility
type JitServer interface {
	Calculate(context.Context, *CalculationRequest) (*CalculationResponse, error)
	mustEmbedUnimplementedJitServer()
}

// UnimplementedJitServer must be embedded to have forward compatible implementations.
type UnimplementedJitServer struct {
}

func (UnimplementedJitServer) Calculate(context.Context, *CalculationRequest) (*CalculationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}
func (UnimplementedJitServer) mustEmbedUnimplementedJitServer() {}

// UnsafeJitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JitServer will
// result in compilation errors.
type UnsafeJitServer interface {
	mustEmbedUnimplementedJitServer()
}

func RegisterJitServer(s grpc.ServiceRegistrar, srv JitServer) {
	s.RegisterService(&Jit_ServiceDesc, srv)
}

func _Jit_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JitServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jit_Calculate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JitServer).Calculate(ctx, req.(*CalculationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Jit_ServiceDesc is the grpc.ServiceDesc for Jit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Jit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Jit",
	HandlerType: (*JitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _Jit_Calculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/jit.proto",
}
